### ISSUE TITLE
centos抓mysql报错

### ISSUE THREAD

**Issue by lanybass** [40t/go-sniffer#12]
2018-11-01 16:21:39| cli -> ser |Stm id[10]: 'SELECT `domain` FROM `xxx` WHERE  `ticket` = ? LIMIT 1  ';
set @p0 = 'xxxxx';
Execute stm id[10]:  using @p0;
Drop stm id[10];

# Start new stream: 127.0.0.1->127.0.0.1 33134->3306
2018/11/01 16:21:39 ERR : Not found stm id 19
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7885cf]

goroutine 44 [running]:
github.com/40t/go-sniffer/plugSrc/mysql/build.(*stream).resolveClientPacket(0xc420401590, 0xc42051f200, 0x1e, 0x600, 0x0)
        /Golang/src/github.com/40t/go-sniffer/plugSrc/mysql/build/entry.go:314 +0x4ef
github.com/40t/go-sniffer/plugSrc/mysql/build.(*stream).resolve(0xc420401590)
        /Golang/src/github.com/40t/go-sniffer/plugSrc/mysql/build/entry.go:192 +0x98
created by github.com/40t/go-sniffer/plugSrc/mysql/build.(*Mysql).ResolveStream
        /Golang/src/github.com/40t/go-sniffer/plugSrc/mysql/build/entry.go:71 +0x42e

**Comment by lanybass** [comment]
# Start new stream: 127.0.0.1->127.0.0.1 32954->3306
2018-11-01 16:21:35| ser -> cli |【Ok】 Effect Row:0
2018-11-01 16:21:35| cli -> ser |【Pretreatment】SHOW COLUMNS FROM `xxx`
2018-11-01 16:21:35| cli -> ser |Stm id[3]: 'SHOW COLUMNS FROM `xxx`';
Execute stm id[3]: ;
Drop stm id[3];

# Start new stream: 127.0.0.1->127.0.0.1 3306->32954
2018/11/01 16:21:35 ERR : Not found stm id 19
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7885cf]

goroutine 24 [running]:
github.com/40t/go-sniffer/plugSrc/mysql/build.(*stream).resolveClientPacket(0xc42041a320, 0xc420418000, 0x1f, 0x600, 0x0)
        /Golang/src/github.com/40t/go-sniffer/plugSrc/mysql/build/entry.go:314 +0x4ef
github.com/40t/go-sniffer/plugSrc/mysql/build.(*stream).resolve(0xc42041a320)
        /Golang/src/github.com/40t/go-sniffer/plugSrc/mysql/build/entry.go:192 +0x98
created by github.com/40t/go-sniffer/plugSrc/mysql/build.(*Mysql).ResolveStream
        /Golang/src/github.com/40t/go-sniffer/plugSrc/mysql/build/entry.go:71 +0x42e

**Comment by 40t** [comment]
这里确实有小概率的情况会出现这种问题，我现在还在开发PostgreSQL协议，之后我会处理一下，已记录此问题，感谢反馈.

**Comment by lanybass** [comment]
不是小概率，我现在正在生产环境上抓，每次都持续不到2秒就会报这个.
还需要什么信息我可以马上协助

**Comment by 40t** [comment]
> 不是小概率，我现在正在生产环境上抓，每次都持续不到2秒就会报这个.
> 还需要什么信息我可以马上协助

我这边做了一下处理，重新git pull  一下

**Comment by lanybass** [comment]
OK,没毛病了~

**Comment by lanybass** [comment]
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:28 ERR : Not found stm id 19
2018/11/01 17:37:29 ERR : Not found stm id 19
2018/11/01 17:37:29 ERR : Not found stm id 19
2018/11/01 17:37:29 ERR : Not found stm id 19
2018/11/01 17:37:29 ERR : Not found stm id 19
2018/11/01 17:37:29 ERR : Not found stm id 19
2018/11/01 17:37:29 ERR : Not found stm id 19
2018/11/01 17:37:30 ERR : Not found stm id 19
2018/11/01 17:37:30 ERR : Not found stm id 19
2018/11/01 17:37:30 ERR : Not found stm id 19
2018/11/01 17:37:30 ERR : Not found stm id 19
2018/11/01 17:37:30 ERR : Not found stm id 19
2018/11/01 17:37:30 ERR : Not found stm id 19
2018/11/01 17:37:40 ERR : Not found stm packet
2018/11/01 17:37:47 ERR : Not found stm packet
2018/11/01 17:37:52 ERR : Not found stm packet
2018/11/01 17:37:52 ERR : Not found stm packet
2018/11/01 17:38:06 ERR : Not found stm packet
2018/11/01 17:38:09 ERR : Not found stm packet
2018/11/01 17:38:12 ERR : Not found stm packet
2018/11/01 17:38:13 ERR : Not found stm packet
2018/11/01 17:38:20 ERR : Not found stm packet
2018/11/01 17:38:29 ERR : Not found stm packet
2018/11/01 17:38:43 ERR : Not found stm packet
这些有空再研究吧

**Comment by 40t** [comment]
mysql  预处理语句简要：第一个包：stmId = 19 , 客户端->服务器 select * from where id = ? ， 第二个包 客户端->服务器 对应stmid=19, set ? = 11 是一个绑定过程，在抓取的过程中发现 只抓到第二个包 里面的序号是19 ，但是 找不到 对应的第一个包19。
原因: 
1.可能第一个包 已经执行了，但是此时没有开启go-sniffer抓取。
2.可能第一个包 不存在 出现了问题.

**Comment by lanybass** [comment]
> mysql 预处理语句简要：第一个包：stmId = 19 , 客户端->服务器 select * from where id = ? ， 第二个包 客户端->服务器 对应stmid=19, set ? = 11 是一个绑定过程，在抓取的过程中发现 只抓到第二个包 里面的序号是19 ，但是 找不到 对应的第一个包19。
> 原因:
> 1.可能第一个包 已经执行了，但是此时没有开启go-sniffer抓取。
> 2.可能第一个包 不存在 出现了问题.

嗯，原因1可能是对的，就开头几秒存在 Not found stm id 19  
但是后面每分钟都断断续续的出现  Not found stm packet 就不是了.
