### ISSUE TITLE
unrecognized import path "plugin"

### ISSUE THREAD

**Issue by anhk** [40t/go-sniffer#18]
[root❄anhk-pc:go-sniffer]☭ GOPATH=$(pwd)/vendor go get github.com/40t/go-sniffer
package plugin: unrecognized import path "plugin" (import path does not begin with hostname)
[root❄anhk-pc:go-sniffer]☭

**Comment by 40t** [comment]
https://blog.csdn.net/ucmir183/article/details/78418409  排错一下

**Comment by anhk** [comment]
golang版本问题
